/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'topic-research': EventHandler<never, { topic: 'content.research.completed'; data: never }>
    'strategy-optimizer': CronHandler<never>
    'quality-assurance': EventHandler<{ platformContents: { blog?: string; twitter?: string[]; linkedin?: string; newsletter?: string }; context: { topic: string; audience: { persona: string; language?: string; readingLevel?: 'beginner' | 'intermediate' | 'expert' } } }, never>
    'performance-tracker': EventHandler<never, never>
    'multi-platform-publisher': EventHandler<{ contents: { blog?: string; twitter?: string[]; linkedin?: string; newsletter?: string }; schedule?: { when?: string }; metadata: { topic: string; audience: { persona: string; language: string } } }, { topic: 'content.published'; data: never }>
    'content-request': ApiRouteHandler<{ topic?: string; sourceUrl?: string; targetPlatforms: 'blog' | 'twitter' | 'linkedin' | 'newsletter'[]; urgency?: 'low' | 'normal' | 'high'; audience: { persona: string; language?: string; readingLevel?: 'beginner' | 'intermediate' | 'expert' } }, unknown, { topic: 'content.request.received'; data: never }>
    'ai-content-generator': EventHandler<never, { topic: 'content.generation.completed'; data: { platformContents: { blog?: string; twitter?: string[]; linkedin?: string; newsletter?: string }; context: { topic: string; audience: { persona: string; language?: string; readingLevel?: 'beginner' | 'intermediate' | 'expert' } } } }>
  }
}